// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: barq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InsertStatusState int32

const (
	InsertStatusState_INSERT_STATUS_STATE_UNSPECIFIED InsertStatusState = 0
	InsertStatusState_INSERT_STATUS_STATE_QUEUED      InsertStatusState = 1
	InsertStatusState_INSERT_STATUS_STATE_PROCESSING  InsertStatusState = 2
	InsertStatusState_INSERT_STATUS_STATE_SUCCEEDED   InsertStatusState = 3
	InsertStatusState_INSERT_STATUS_STATE_FAILED      InsertStatusState = 4
)

// Enum value maps for InsertStatusState.
var (
	InsertStatusState_name = map[int32]string{
		0: "INSERT_STATUS_STATE_UNSPECIFIED",
		1: "INSERT_STATUS_STATE_QUEUED",
		2: "INSERT_STATUS_STATE_PROCESSING",
		3: "INSERT_STATUS_STATE_SUCCEEDED",
		4: "INSERT_STATUS_STATE_FAILED",
	}
	InsertStatusState_value = map[string]int32{
		"INSERT_STATUS_STATE_UNSPECIFIED": 0,
		"INSERT_STATUS_STATE_QUEUED":      1,
		"INSERT_STATUS_STATE_PROCESSING":  2,
		"INSERT_STATUS_STATE_SUCCEEDED":   3,
		"INSERT_STATUS_STATE_FAILED":      4,
	}
)

func (x InsertStatusState) Enum() *InsertStatusState {
	p := new(InsertStatusState)
	*p = x
	return p
}

func (x InsertStatusState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InsertStatusState) Descriptor() protoreflect.EnumDescriptor {
	return file_barq_proto_enumTypes[0].Descriptor()
}

func (InsertStatusState) Type() protoreflect.EnumType {
	return &file_barq_proto_enumTypes[0]
}

func (x InsertStatusState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InsertStatusState.Descriptor instead.
func (InsertStatusState) EnumDescriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{0}
}

type Consistency int32

const (
	Consistency_CONSISTENCY_UNSPECIFIED Consistency = 0
	Consistency_CONSISTENCY_PRIMARY     Consistency = 1
	Consistency_CONSISTENCY_FOLLOWERS   Consistency = 2
	Consistency_CONSISTENCY_ANY         Consistency = 3
)

// Enum value maps for Consistency.
var (
	Consistency_name = map[int32]string{
		0: "CONSISTENCY_UNSPECIFIED",
		1: "CONSISTENCY_PRIMARY",
		2: "CONSISTENCY_FOLLOWERS",
		3: "CONSISTENCY_ANY",
	}
	Consistency_value = map[string]int32{
		"CONSISTENCY_UNSPECIFIED": 0,
		"CONSISTENCY_PRIMARY":     1,
		"CONSISTENCY_FOLLOWERS":   2,
		"CONSISTENCY_ANY":         3,
	}
)

func (x Consistency) Enum() *Consistency {
	p := new(Consistency)
	*p = x
	return p
}

func (x Consistency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Consistency) Descriptor() protoreflect.EnumDescriptor {
	return file_barq_proto_enumTypes[1].Descriptor()
}

func (Consistency) Type() protoreflect.EnumType {
	return &file_barq_proto_enumTypes[1]
}

func (x Consistency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Consistency.Descriptor instead.
func (Consistency) EnumDescriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{1}
}

type MetricKind int32

const (
	MetricKind_METRIC_KIND_UNSPECIFIED MetricKind = 0
	MetricKind_METRIC_KIND_COUNTER     MetricKind = 1
	MetricKind_METRIC_KIND_GAUGE       MetricKind = 2
	MetricKind_METRIC_KIND_HISTOGRAM   MetricKind = 3
)

// Enum value maps for MetricKind.
var (
	MetricKind_name = map[int32]string{
		0: "METRIC_KIND_UNSPECIFIED",
		1: "METRIC_KIND_COUNTER",
		2: "METRIC_KIND_GAUGE",
		3: "METRIC_KIND_HISTOGRAM",
	}
	MetricKind_value = map[string]int32{
		"METRIC_KIND_UNSPECIFIED": 0,
		"METRIC_KIND_COUNTER":     1,
		"METRIC_KIND_GAUGE":       2,
		"METRIC_KIND_HISTOGRAM":   3,
	}
)

func (x MetricKind) Enum() *MetricKind {
	p := new(MetricKind)
	*p = x
	return p
}

func (x MetricKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricKind) Descriptor() protoreflect.EnumDescriptor {
	return file_barq_proto_enumTypes[2].Descriptor()
}

func (MetricKind) Type() protoreflect.EnumType {
	return &file_barq_proto_enumTypes[2]
}

func (x MetricKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricKind.Descriptor instead.
func (MetricKind) EnumDescriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{2}
}

type SegmentState int32

const (
	SegmentState_SEGMENT_STATE_UNSPECIFIED SegmentState = 0
	SegmentState_SEGMENT_STATE_GROWING     SegmentState = 1
	SegmentState_SEGMENT_STATE_SEALED      SegmentState = 2
	SegmentState_SEGMENT_STATE_COMPACTED   SegmentState = 3
)

// Enum value maps for SegmentState.
var (
	SegmentState_name = map[int32]string{
		0: "SEGMENT_STATE_UNSPECIFIED",
		1: "SEGMENT_STATE_GROWING",
		2: "SEGMENT_STATE_SEALED",
		3: "SEGMENT_STATE_COMPACTED",
	}
	SegmentState_value = map[string]int32{
		"SEGMENT_STATE_UNSPECIFIED": 0,
		"SEGMENT_STATE_GROWING":     1,
		"SEGMENT_STATE_SEALED":      2,
		"SEGMENT_STATE_COMPACTED":   3,
	}
)

func (x SegmentState) Enum() *SegmentState {
	p := new(SegmentState)
	*p = x
	return p
}

func (x SegmentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SegmentState) Descriptor() protoreflect.EnumDescriptor {
	return file_barq_proto_enumTypes[3].Descriptor()
}

func (SegmentState) Type() protoreflect.EnumType {
	return &file_barq_proto_enumTypes[3]
}

func (x SegmentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SegmentState.Descriptor instead.
func (SegmentState) EnumDescriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{3}
}

type ClusterMode int32

const (
	ClusterMode_CLUSTER_MODE_UNSPECIFIED        ClusterMode = 0
	ClusterMode_CLUSTER_MODE_SINGLE_NODE        ClusterMode = 1
	ClusterMode_CLUSTER_MODE_ROUTED_REPLICATION ClusterMode = 2
	ClusterMode_CLUSTER_MODE_CONSENSUS_BACKED   ClusterMode = 3
)

// Enum value maps for ClusterMode.
var (
	ClusterMode_name = map[int32]string{
		0: "CLUSTER_MODE_UNSPECIFIED",
		1: "CLUSTER_MODE_SINGLE_NODE",
		2: "CLUSTER_MODE_ROUTED_REPLICATION",
		3: "CLUSTER_MODE_CONSENSUS_BACKED",
	}
	ClusterMode_value = map[string]int32{
		"CLUSTER_MODE_UNSPECIFIED":        0,
		"CLUSTER_MODE_SINGLE_NODE":        1,
		"CLUSTER_MODE_ROUTED_REPLICATION": 2,
		"CLUSTER_MODE_CONSENSUS_BACKED":   3,
	}
)

func (x ClusterMode) Enum() *ClusterMode {
	p := new(ClusterMode)
	*p = x
	return p
}

func (x ClusterMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClusterMode) Descriptor() protoreflect.EnumDescriptor {
	return file_barq_proto_enumTypes[4].Descriptor()
}

func (ClusterMode) Type() protoreflect.EnumType {
	return &file_barq_proto_enumTypes[4]
}

func (x ClusterMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClusterMode.Descriptor instead.
func (ClusterMode) EnumDescriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{4}
}

type WriteDurability int32

const (
	WriteDurability_WRITE_DURABILITY_UNSPECIFIED      WriteDurability = 0
	WriteDurability_WRITE_DURABILITY_NODE_LOCAL       WriteDurability = 1
	WriteDurability_WRITE_DURABILITY_PRIMARY_ONLY     WriteDurability = 2
	WriteDurability_WRITE_DURABILITY_CONSENSUS_QUORUM WriteDurability = 3
)

// Enum value maps for WriteDurability.
var (
	WriteDurability_name = map[int32]string{
		0: "WRITE_DURABILITY_UNSPECIFIED",
		1: "WRITE_DURABILITY_NODE_LOCAL",
		2: "WRITE_DURABILITY_PRIMARY_ONLY",
		3: "WRITE_DURABILITY_CONSENSUS_QUORUM",
	}
	WriteDurability_value = map[string]int32{
		"WRITE_DURABILITY_UNSPECIFIED":      0,
		"WRITE_DURABILITY_NODE_LOCAL":       1,
		"WRITE_DURABILITY_PRIMARY_ONLY":     2,
		"WRITE_DURABILITY_CONSENSUS_QUORUM": 3,
	}
)

func (x WriteDurability) Enum() *WriteDurability {
	p := new(WriteDurability)
	*p = x
	return p
}

func (x WriteDurability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WriteDurability) Descriptor() protoreflect.EnumDescriptor {
	return file_barq_proto_enumTypes[5].Descriptor()
}

func (WriteDurability) Type() protoreflect.EnumType {
	return &file_barq_proto_enumTypes[5]
}

func (x WriteDurability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WriteDurability.Descriptor instead.
func (WriteDurability) EnumDescriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{5}
}

type IndexState int32

const (
	IndexState_INDEX_STATE_UNSPECIFIED IndexState = 0
	IndexState_INDEX_STATE_BUILDING    IndexState = 1
	IndexState_INDEX_STATE_READY       IndexState = 2
	IndexState_INDEX_STATE_STALE       IndexState = 3
)

// Enum value maps for IndexState.
var (
	IndexState_name = map[int32]string{
		0: "INDEX_STATE_UNSPECIFIED",
		1: "INDEX_STATE_BUILDING",
		2: "INDEX_STATE_READY",
		3: "INDEX_STATE_STALE",
	}
	IndexState_value = map[string]int32{
		"INDEX_STATE_UNSPECIFIED": 0,
		"INDEX_STATE_BUILDING":    1,
		"INDEX_STATE_READY":       2,
		"INDEX_STATE_STALE":       3,
	}
)

func (x IndexState) Enum() *IndexState {
	p := new(IndexState)
	*p = x
	return p
}

func (x IndexState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IndexState) Descriptor() protoreflect.EnumDescriptor {
	return file_barq_proto_enumTypes[6].Descriptor()
}

func (IndexState) Type() protoreflect.EnumType {
	return &file_barq_proto_enumTypes[6]
}

func (x IndexState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IndexState.Descriptor instead.
func (IndexState) EnumDescriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{6}
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_barq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{0}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_barq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_barq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_barq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type CreateCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dimension     uint32                 `protobuf:"varint,2,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Metric        string                 `protobuf:"bytes,3,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionRequest) Reset() {
	*x = CreateCollectionRequest{}
	mi := &file_barq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionRequest) ProtoMessage() {}

func (x *CreateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionRequest.ProtoReflect.Descriptor instead.
func (*CreateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCollectionRequest) GetDimension() uint32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *CreateCollectionRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

type CreateCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionResponse) Reset() {
	*x = CreateCollectionResponse{}
	mi := &file_barq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionResponse) ProtoMessage() {}

func (x *CreateCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionResponse.ProtoReflect.Descriptor instead.
func (*CreateCollectionResponse) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCollectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type InsertOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WaitForCommit bool                   `protobuf:"varint,1,opt,name=wait_for_commit,json=waitForCommit,proto3" json:"wait_for_commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertOptions) Reset() {
	*x = InsertOptions{}
	mi := &file_barq_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertOptions) ProtoMessage() {}

func (x *InsertOptions) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertOptions.ProtoReflect.Descriptor instead.
func (*InsertOptions) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{6}
}

func (x *InsertOptions) GetWaitForCommit() bool {
	if x != nil {
		return x.WaitForCommit
	}
	return false
}

type InsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Vector        []float32              `protobuf:"fixed32,3,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,4,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	Options       *InsertOptions         `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_barq_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{7}
}

func (x *InsertRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *InsertRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InsertRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *InsertRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *InsertRequest) GetOptions() *InsertOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_barq_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{8}
}

func (x *InsertResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type InsertAsyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertAsyncResponse) Reset() {
	*x = InsertAsyncResponse{}
	mi := &file_barq_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertAsyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertAsyncResponse) ProtoMessage() {}

func (x *InsertAsyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertAsyncResponse.ProtoReflect.Descriptor instead.
func (*InsertAsyncResponse) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{9}
}

func (x *InsertAsyncResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *InsertAsyncResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GetInsertStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInsertStatusRequest) Reset() {
	*x = GetInsertStatusRequest{}
	mi := &file_barq_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInsertStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInsertStatusRequest) ProtoMessage() {}

func (x *GetInsertStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInsertStatusRequest.ProtoReflect.Descriptor instead.
func (*GetInsertStatusRequest) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{10}
}

func (x *GetInsertStatusRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GetInsertStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	State         InsertStatusState      `protobuf:"varint,2,opt,name=state,proto3,enum=barq.InsertStatusState" json:"state,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInsertStatusResponse) Reset() {
	*x = GetInsertStatusResponse{}
	mi := &file_barq_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInsertStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInsertStatusResponse) ProtoMessage() {}

func (x *GetInsertStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInsertStatusResponse.ProtoReflect.Descriptor instead.
func (*GetInsertStatusResponse) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{11}
}

func (x *GetInsertStatusResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetInsertStatusResponse) GetState() InsertStatusState {
	if x != nil {
		return x.State
	}
	return InsertStatusState_INSERT_STATUS_STATE_UNSPECIFIED
}

func (x *GetInsertStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type InsertDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Vector        []float32              `protobuf:"fixed32,3,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,4,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertDocumentRequest) Reset() {
	*x = InsertDocumentRequest{}
	mi := &file_barq_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertDocumentRequest) ProtoMessage() {}

func (x *InsertDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertDocumentRequest.ProtoReflect.Descriptor instead.
func (*InsertDocumentRequest) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{12}
}

func (x *InsertDocumentRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *InsertDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InsertDocumentRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *InsertDocumentRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type InsertDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertDocumentResponse) Reset() {
	*x = InsertDocumentResponse{}
	mi := &file_barq_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertDocumentResponse) ProtoMessage() {}

func (x *InsertDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertDocumentResponse.ProtoReflect.Descriptor instead.
func (*InsertDocumentResponse) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{13}
}

func (x *InsertDocumentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SearchOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consistency   Consistency            `protobuf:"varint,1,opt,name=consistency,proto3,enum=barq.Consistency" json:"consistency,omitempty"`
	AllowFallback bool                   `protobuf:"varint,2,opt,name=allow_fallback,json=allowFallback,proto3" json:"allow_fallback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchOptions) Reset() {
	*x = SearchOptions{}
	mi := &file_barq_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchOptions) ProtoMessage() {}

func (x *SearchOptions) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchOptions.ProtoReflect.Descriptor instead.
func (*SearchOptions) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{14}
}

func (x *SearchOptions) GetConsistency() Consistency {
	if x != nil {
		return x.Consistency
	}
	return Consistency_CONSISTENCY_UNSPECIFIED
}

func (x *SearchOptions) GetAllowFallback() bool {
	if x != nil {
		return x.AllowFallback
	}
	return false
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Vector        []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	TopK          uint32                 `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Options       *SearchOptions         `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_barq_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{15}
}

func (x *SearchRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *SearchRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *SearchRequest) GetTopK() uint32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchRequest) GetOptions() *SearchOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,3,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_barq_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{16}
}

func (x *SearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResult) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_barq_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{17}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_barq_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{18}
}

type MetricDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind          MetricKind             `protobuf:"varint,2,opt,name=kind,proto3,enum=barq.MetricKind" json:"kind,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Unit          string                 `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	Labels        []string               `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricDefinition) Reset() {
	*x = MetricDefinition{}
	mi := &file_barq_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricDefinition) ProtoMessage() {}

func (x *MetricDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricDefinition.ProtoReflect.Descriptor instead.
func (*MetricDefinition) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{19}
}

func (x *MetricDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricDefinition) GetKind() MetricKind {
	if x != nil {
		return x.Kind
	}
	return MetricKind_METRIC_KIND_UNSPECIFIED
}

func (x *MetricDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MetricDefinition) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *MetricDefinition) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type TenantMemorySample struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Tenant                    string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	ResidentVectorMemoryBytes uint64                 `protobuf:"varint,2,opt,name=resident_vector_memory_bytes,json=residentVectorMemoryBytes,proto3" json:"resident_vector_memory_bytes,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *TenantMemorySample) Reset() {
	*x = TenantMemorySample{}
	mi := &file_barq_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantMemorySample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantMemorySample) ProtoMessage() {}

func (x *TenantMemorySample) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantMemorySample.ProtoReflect.Descriptor instead.
func (*TenantMemorySample) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{20}
}

func (x *TenantMemorySample) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *TenantMemorySample) GetResidentVectorMemoryBytes() uint64 {
	if x != nil {
		return x.ResidentVectorMemoryBytes
	}
	return 0
}

type CollectionMemorySample struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Tenant                    string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Collection                string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	ResidentVectorMemoryBytes uint64                 `protobuf:"varint,3,opt,name=resident_vector_memory_bytes,json=residentVectorMemoryBytes,proto3" json:"resident_vector_memory_bytes,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CollectionMemorySample) Reset() {
	*x = CollectionMemorySample{}
	mi := &file_barq_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionMemorySample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionMemorySample) ProtoMessage() {}

func (x *CollectionMemorySample) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionMemorySample.ProtoReflect.Descriptor instead.
func (*CollectionMemorySample) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{21}
}

func (x *CollectionMemorySample) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *CollectionMemorySample) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *CollectionMemorySample) GetResidentVectorMemoryBytes() uint64 {
	if x != nil {
		return x.ResidentVectorMemoryBytes
	}
	return 0
}

type CollectionWalSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Entries       uint64                 `protobuf:"varint,3,opt,name=entries,proto3" json:"entries,omitempty"`
	Bytes         uint64                 `protobuf:"varint,4,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionWalSample) Reset() {
	*x = CollectionWalSample{}
	mi := &file_barq_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionWalSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionWalSample) ProtoMessage() {}

func (x *CollectionWalSample) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionWalSample.ProtoReflect.Descriptor instead.
func (*CollectionWalSample) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{22}
}

func (x *CollectionWalSample) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *CollectionWalSample) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *CollectionWalSample) GetEntries() uint64 {
	if x != nil {
		return x.Entries
	}
	return 0
}

func (x *CollectionWalSample) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

type CollectionSegmentFileSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	State         SegmentState           `protobuf:"varint,3,opt,name=state,proto3,enum=barq.SegmentState" json:"state,omitempty"`
	Count         uint64                 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionSegmentFileSample) Reset() {
	*x = CollectionSegmentFileSample{}
	mi := &file_barq_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionSegmentFileSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionSegmentFileSample) ProtoMessage() {}

func (x *CollectionSegmentFileSample) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionSegmentFileSample.ProtoReflect.Descriptor instead.
func (*CollectionSegmentFileSample) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{23}
}

func (x *CollectionSegmentFileSample) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *CollectionSegmentFileSample) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *CollectionSegmentFileSample) GetState() SegmentState {
	if x != nil {
		return x.State
	}
	return SegmentState_SEGMENT_STATE_UNSPECIFIED
}

func (x *CollectionSegmentFileSample) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CollectionSegmentStateSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	State         SegmentState           `protobuf:"varint,3,opt,name=state,proto3,enum=barq.SegmentState" json:"state,omitempty"`
	Active        bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionSegmentStateSample) Reset() {
	*x = CollectionSegmentStateSample{}
	mi := &file_barq_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionSegmentStateSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionSegmentStateSample) ProtoMessage() {}

func (x *CollectionSegmentStateSample) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionSegmentStateSample.ProtoReflect.Descriptor instead.
func (*CollectionSegmentStateSample) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{24}
}

func (x *CollectionSegmentStateSample) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *CollectionSegmentStateSample) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *CollectionSegmentStateSample) GetState() SegmentState {
	if x != nil {
		return x.State
	}
	return SegmentState_SEGMENT_STATE_UNSPECIFIED
}

func (x *CollectionSegmentStateSample) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type StorageMetrics struct {
	state                          protoimpl.MessageState          `protogen:"open.v1"`
	RefreshCount                   uint64                          `protobuf:"varint,1,opt,name=refresh_count,json=refreshCount,proto3" json:"refresh_count,omitempty"`
	TotalResidentVectorMemoryBytes uint64                          `protobuf:"varint,2,opt,name=total_resident_vector_memory_bytes,json=totalResidentVectorMemoryBytes,proto3" json:"total_resident_vector_memory_bytes,omitempty"`
	WalAppendsTotal                uint64                          `protobuf:"varint,3,opt,name=wal_appends_total,json=walAppendsTotal,proto3" json:"wal_appends_total,omitempty"`
	WalBytesWrittenTotal           uint64                          `protobuf:"varint,4,opt,name=wal_bytes_written_total,json=walBytesWrittenTotal,proto3" json:"wal_bytes_written_total,omitempty"`
	CompactionsTotal               uint64                          `protobuf:"varint,5,opt,name=compactions_total,json=compactionsTotal,proto3" json:"compactions_total,omitempty"`
	TenantMemoryBytes              []*TenantMemorySample           `protobuf:"bytes,6,rep,name=tenant_memory_bytes,json=tenantMemoryBytes,proto3" json:"tenant_memory_bytes,omitempty"`
	CollectionMemoryBytes          []*CollectionMemorySample       `protobuf:"bytes,7,rep,name=collection_memory_bytes,json=collectionMemoryBytes,proto3" json:"collection_memory_bytes,omitempty"`
	CollectionWal                  []*CollectionWalSample          `protobuf:"bytes,8,rep,name=collection_wal,json=collectionWal,proto3" json:"collection_wal,omitempty"`
	CollectionSegmentFiles         []*CollectionSegmentFileSample  `protobuf:"bytes,9,rep,name=collection_segment_files,json=collectionSegmentFiles,proto3" json:"collection_segment_files,omitempty"`
	CollectionSegmentStates        []*CollectionSegmentStateSample `protobuf:"bytes,10,rep,name=collection_segment_states,json=collectionSegmentStates,proto3" json:"collection_segment_states,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *StorageMetrics) Reset() {
	*x = StorageMetrics{}
	mi := &file_barq_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageMetrics) ProtoMessage() {}

func (x *StorageMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageMetrics.ProtoReflect.Descriptor instead.
func (*StorageMetrics) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{25}
}

func (x *StorageMetrics) GetRefreshCount() uint64 {
	if x != nil {
		return x.RefreshCount
	}
	return 0
}

func (x *StorageMetrics) GetTotalResidentVectorMemoryBytes() uint64 {
	if x != nil {
		return x.TotalResidentVectorMemoryBytes
	}
	return 0
}

func (x *StorageMetrics) GetWalAppendsTotal() uint64 {
	if x != nil {
		return x.WalAppendsTotal
	}
	return 0
}

func (x *StorageMetrics) GetWalBytesWrittenTotal() uint64 {
	if x != nil {
		return x.WalBytesWrittenTotal
	}
	return 0
}

func (x *StorageMetrics) GetCompactionsTotal() uint64 {
	if x != nil {
		return x.CompactionsTotal
	}
	return 0
}

func (x *StorageMetrics) GetTenantMemoryBytes() []*TenantMemorySample {
	if x != nil {
		return x.TenantMemoryBytes
	}
	return nil
}

func (x *StorageMetrics) GetCollectionMemoryBytes() []*CollectionMemorySample {
	if x != nil {
		return x.CollectionMemoryBytes
	}
	return nil
}

func (x *StorageMetrics) GetCollectionWal() []*CollectionWalSample {
	if x != nil {
		return x.CollectionWal
	}
	return nil
}

func (x *StorageMetrics) GetCollectionSegmentFiles() []*CollectionSegmentFileSample {
	if x != nil {
		return x.CollectionSegmentFiles
	}
	return nil
}

func (x *StorageMetrics) GetCollectionSegmentStates() []*CollectionSegmentStateSample {
	if x != nil {
		return x.CollectionSegmentStates
	}
	return nil
}

type GetMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Definitions   []*MetricDefinition    `protobuf:"bytes,1,rep,name=definitions,proto3" json:"definitions,omitempty"`
	Storage       *StorageMetrics        `protobuf:"bytes,2,opt,name=storage,proto3" json:"storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_barq_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{26}
}

func (x *GetMetricsResponse) GetDefinitions() []*MetricDefinition {
	if x != nil {
		return x.Definitions
	}
	return nil
}

func (x *GetMetricsResponse) GetStorage() *StorageMetrics {
	if x != nil {
		return x.Storage
	}
	return nil
}

type GetClusterStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterStatusRequest) Reset() {
	*x = GetClusterStatusRequest{}
	mi := &file_barq_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterStatusRequest) ProtoMessage() {}

func (x *GetClusterStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterStatusRequest.ProtoReflect.Descriptor instead.
func (*GetClusterStatusRequest) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{27}
}

type GetClusterStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Mode            ClusterMode            `protobuf:"varint,2,opt,name=mode,proto3,enum=barq.ClusterMode" json:"mode,omitempty"`
	WriteDurability WriteDurability        `protobuf:"varint,3,opt,name=write_durability,json=writeDurability,proto3,enum=barq.WriteDurability" json:"write_durability,omitempty"`
	ShardCount      uint32                 `protobuf:"varint,4,opt,name=shard_count,json=shardCount,proto3" json:"shard_count,omitempty"`
	NodeCount       uint64                 `protobuf:"varint,5,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetClusterStatusResponse) Reset() {
	*x = GetClusterStatusResponse{}
	mi := &file_barq_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterStatusResponse) ProtoMessage() {}

func (x *GetClusterStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterStatusResponse.ProtoReflect.Descriptor instead.
func (*GetClusterStatusResponse) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{28}
}

func (x *GetClusterStatusResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetClusterStatusResponse) GetMode() ClusterMode {
	if x != nil {
		return x.Mode
	}
	return ClusterMode_CLUSTER_MODE_UNSPECIFIED
}

func (x *GetClusterStatusResponse) GetWriteDurability() WriteDurability {
	if x != nil {
		return x.WriteDurability
	}
	return WriteDurability_WRITE_DURABILITY_UNSPECIFIED
}

func (x *GetClusterStatusResponse) GetShardCount() uint32 {
	if x != nil {
		return x.ShardCount
	}
	return 0
}

func (x *GetClusterStatusResponse) GetNodeCount() uint64 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

type GetSegmentInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSegmentInfoRequest) Reset() {
	*x = GetSegmentInfoRequest{}
	mi := &file_barq_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSegmentInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSegmentInfoRequest) ProtoMessage() {}

func (x *GetSegmentInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSegmentInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSegmentInfoRequest) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{29}
}

func (x *GetSegmentInfoRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

type SegmentCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         SegmentState           `protobuf:"varint,1,opt,name=state,proto3,enum=barq.SegmentState" json:"state,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentCount) Reset() {
	*x = SegmentCount{}
	mi := &file_barq_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentCount) ProtoMessage() {}

func (x *SegmentCount) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentCount.ProtoReflect.Descriptor instead.
func (*SegmentCount) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{30}
}

func (x *SegmentCount) GetState() SegmentState {
	if x != nil {
		return x.State
	}
	return SegmentState_SEGMENT_STATE_UNSPECIFIED
}

func (x *SegmentCount) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CollectionSegmentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	CurrentState  SegmentState           `protobuf:"varint,3,opt,name=current_state,json=currentState,proto3,enum=barq.SegmentState" json:"current_state,omitempty"`
	IndexState    IndexState             `protobuf:"varint,4,opt,name=index_state,json=indexState,proto3,enum=barq.IndexState" json:"index_state,omitempty"`
	SegmentCounts []*SegmentCount        `protobuf:"bytes,5,rep,name=segment_counts,json=segmentCounts,proto3" json:"segment_counts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionSegmentInfo) Reset() {
	*x = CollectionSegmentInfo{}
	mi := &file_barq_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionSegmentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionSegmentInfo) ProtoMessage() {}

func (x *CollectionSegmentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionSegmentInfo.ProtoReflect.Descriptor instead.
func (*CollectionSegmentInfo) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{31}
}

func (x *CollectionSegmentInfo) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *CollectionSegmentInfo) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *CollectionSegmentInfo) GetCurrentState() SegmentState {
	if x != nil {
		return x.CurrentState
	}
	return SegmentState_SEGMENT_STATE_UNSPECIFIED
}

func (x *CollectionSegmentInfo) GetIndexState() IndexState {
	if x != nil {
		return x.IndexState
	}
	return IndexState_INDEX_STATE_UNSPECIFIED
}

func (x *CollectionSegmentInfo) GetSegmentCounts() []*SegmentCount {
	if x != nil {
		return x.SegmentCounts
	}
	return nil
}

type GetSegmentInfoResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Collections   []*CollectionSegmentInfo `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSegmentInfoResponse) Reset() {
	*x = GetSegmentInfoResponse{}
	mi := &file_barq_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSegmentInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSegmentInfoResponse) ProtoMessage() {}

func (x *GetSegmentInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSegmentInfoResponse.ProtoReflect.Descriptor instead.
func (*GetSegmentInfoResponse) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{32}
}

func (x *GetSegmentInfoResponse) GetCollections() []*CollectionSegmentInfo {
	if x != nil {
		return x.Collections
	}
	return nil
}

type SearchQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        []float32              `protobuf:"fixed32,1,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	FilterJson    string                 `protobuf:"bytes,2,opt,name=filter_json,json=filterJson,proto3" json:"filter_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchQuery) Reset() {
	*x = SearchQuery{}
	mi := &file_barq_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchQuery) ProtoMessage() {}

func (x *SearchQuery) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchQuery.ProtoReflect.Descriptor instead.
func (*SearchQuery) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{33}
}

func (x *SearchQuery) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *SearchQuery) GetFilterJson() string {
	if x != nil {
		return x.FilterJson
	}
	return ""
}

type BatchSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Queries       []*SearchQuery         `protobuf:"bytes,2,rep,name=queries,proto3" json:"queries,omitempty"`
	TopK          uint32                 `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSearchRequest) Reset() {
	*x = BatchSearchRequest{}
	mi := &file_barq_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSearchRequest) ProtoMessage() {}

func (x *BatchSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSearchRequest.ProtoReflect.Descriptor instead.
func (*BatchSearchRequest) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{34}
}

func (x *BatchSearchRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *BatchSearchRequest) GetQueries() []*SearchQuery {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *BatchSearchRequest) GetTopK() uint32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type QueryResults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hits          []*SearchResult        `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResults) Reset() {
	*x = QueryResults{}
	mi := &file_barq_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResults) ProtoMessage() {}

func (x *QueryResults) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResults.ProtoReflect.Descriptor instead.
func (*QueryResults) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{35}
}

func (x *QueryResults) GetHits() []*SearchResult {
	if x != nil {
		return x.Hits
	}
	return nil
}

type BatchSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*QueryResults        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSearchResponse) Reset() {
	*x = BatchSearchResponse{}
	mi := &file_barq_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSearchResponse) ProtoMessage() {}

func (x *BatchSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSearchResponse.ProtoReflect.Descriptor instead.
func (*BatchSearchResponse) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{36}
}

func (x *BatchSearchResponse) GetResults() []*QueryResults {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_barq_proto protoreflect.FileDescriptor

const file_barq_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"barq.proto\x12\x04barq\"\x0f\n" +
	"\rStatusRequest\":\n" +
	"\x0eStatusResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x0f\n" +
	"\rHealthRequest\":\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"c\n" +
	"\x17CreateCollectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tdimension\x18\x02 \x01(\rR\tdimension\x12\x16\n" +
	"\x06metric\x18\x03 \x01(\tR\x06metric\"4\n" +
	"\x18CreateCollectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"7\n" +
	"\rInsertOptions\x12&\n" +
	"\x0fwait_for_commit\x18\x01 \x01(\bR\rwaitForCommit\"\xa9\x01\n" +
	"\rInsertRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x16\n" +
	"\x06vector\x18\x03 \x03(\x02R\x06vector\x12!\n" +
	"\fpayload_json\x18\x04 \x01(\tR\vpayloadJson\x12-\n" +
	"\aoptions\x18\x05 \x01(\v2\x13.barq.InsertOptionsR\aoptions\"*\n" +
	"\x0eInsertResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"P\n" +
	"\x13InsertAsyncResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"7\n" +
	"\x16GetInsertStatusRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\x8c\x01\n" +
	"\x17GetInsertStatusResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12-\n" +
	"\x05state\x18\x02 \x01(\x0e2\x17.barq.InsertStatusStateR\x05state\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x82\x01\n" +
	"\x15InsertDocumentRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x16\n" +
	"\x06vector\x18\x03 \x03(\x02R\x06vector\x12!\n" +
	"\fpayload_json\x18\x04 \x01(\tR\vpayloadJson\"2\n" +
	"\x16InsertDocumentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"k\n" +
	"\rSearchOptions\x123\n" +
	"\vconsistency\x18\x01 \x01(\x0e2\x11.barq.ConsistencyR\vconsistency\x12%\n" +
	"\x0eallow_fallback\x18\x02 \x01(\bR\rallowFallback\"\x8b\x01\n" +
	"\rSearchRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x16\n" +
	"\x06vector\x18\x02 \x03(\x02R\x06vector\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\rR\x04topK\x12-\n" +
	"\aoptions\x18\x04 \x01(\v2\x13.barq.SearchOptionsR\aoptions\"W\n" +
	"\fSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12!\n" +
	"\fpayload_json\x18\x03 \x01(\tR\vpayloadJson\">\n" +
	"\x0eSearchResponse\x12,\n" +
	"\aresults\x18\x01 \x03(\v2\x12.barq.SearchResultR\aresults\"\x13\n" +
	"\x11GetMetricsRequest\"\x9a\x01\n" +
	"\x10MetricDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12$\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x10.barq.MetricKindR\x04kind\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\x12\x16\n" +
	"\x06labels\x18\x05 \x03(\tR\x06labels\"m\n" +
	"\x12TenantMemorySample\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12?\n" +
	"\x1cresident_vector_memory_bytes\x18\x02 \x01(\x04R\x19residentVectorMemoryBytes\"\x91\x01\n" +
	"\x16CollectionMemorySample\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12?\n" +
	"\x1cresident_vector_memory_bytes\x18\x03 \x01(\x04R\x19residentVectorMemoryBytes\"}\n" +
	"\x13CollectionWalSample\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12\x18\n" +
	"\aentries\x18\x03 \x01(\x04R\aentries\x12\x14\n" +
	"\x05bytes\x18\x04 \x01(\x04R\x05bytes\"\x95\x01\n" +
	"\x1bCollectionSegmentFileSample\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12(\n" +
	"\x05state\x18\x03 \x01(\x0e2\x12.barq.SegmentStateR\x05state\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x04R\x05count\"\x98\x01\n" +
	"\x1cCollectionSegmentStateSample\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12(\n" +
	"\x05state\x18\x03 \x01(\x0e2\x12.barq.SegmentStateR\x05state\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\"\xb0\x05\n" +
	"\x0eStorageMetrics\x12#\n" +
	"\rrefresh_count\x18\x01 \x01(\x04R\frefreshCount\x12J\n" +
	"\"total_resident_vector_memory_bytes\x18\x02 \x01(\x04R\x1etotalResidentVectorMemoryBytes\x12*\n" +
	"\x11wal_appends_total\x18\x03 \x01(\x04R\x0fwalAppendsTotal\x125\n" +
	"\x17wal_bytes_written_total\x18\x04 \x01(\x04R\x14walBytesWrittenTotal\x12+\n" +
	"\x11compactions_total\x18\x05 \x01(\x04R\x10compactionsTotal\x12H\n" +
	"\x13tenant_memory_bytes\x18\x06 \x03(\v2\x18.barq.TenantMemorySampleR\x11tenantMemoryBytes\x12T\n" +
	"\x17collection_memory_bytes\x18\a \x03(\v2\x1c.barq.CollectionMemorySampleR\x15collectionMemoryBytes\x12@\n" +
	"\x0ecollection_wal\x18\b \x03(\v2\x19.barq.CollectionWalSampleR\rcollectionWal\x12[\n" +
	"\x18collection_segment_files\x18\t \x03(\v2!.barq.CollectionSegmentFileSampleR\x16collectionSegmentFiles\x12^\n" +
	"\x19collection_segment_states\x18\n" +
	" \x03(\v2\".barq.CollectionSegmentStateSampleR\x17collectionSegmentStates\"~\n" +
	"\x12GetMetricsResponse\x128\n" +
	"\vdefinitions\x18\x01 \x03(\v2\x16.barq.MetricDefinitionR\vdefinitions\x12.\n" +
	"\astorage\x18\x02 \x01(\v2\x14.barq.StorageMetricsR\astorage\"\x19\n" +
	"\x17GetClusterStatusRequest\"\xdc\x01\n" +
	"\x18GetClusterStatusResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12%\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x11.barq.ClusterModeR\x04mode\x12@\n" +
	"\x10write_durability\x18\x03 \x01(\x0e2\x15.barq.WriteDurabilityR\x0fwriteDurability\x12\x1f\n" +
	"\vshard_count\x18\x04 \x01(\rR\n" +
	"shardCount\x12\x1d\n" +
	"\n" +
	"node_count\x18\x05 \x01(\x04R\tnodeCount\"7\n" +
	"\x15GetSegmentInfoRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\"N\n" +
	"\fSegmentCount\x12(\n" +
	"\x05state\x18\x01 \x01(\x0e2\x12.barq.SegmentStateR\x05state\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\"\xf6\x01\n" +
	"\x15CollectionSegmentInfo\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x127\n" +
	"\rcurrent_state\x18\x03 \x01(\x0e2\x12.barq.SegmentStateR\fcurrentState\x121\n" +
	"\vindex_state\x18\x04 \x01(\x0e2\x10.barq.IndexStateR\n" +
	"indexState\x129\n" +
	"\x0esegment_counts\x18\x05 \x03(\v2\x12.barq.SegmentCountR\rsegmentCounts\"W\n" +
	"\x16GetSegmentInfoResponse\x12=\n" +
	"\vcollections\x18\x01 \x03(\v2\x1b.barq.CollectionSegmentInfoR\vcollections\"F\n" +
	"\vSearchQuery\x12\x16\n" +
	"\x06vector\x18\x01 \x03(\x02R\x06vector\x12\x1f\n" +
	"\vfilter_json\x18\x02 \x01(\tR\n" +
	"filterJson\"v\n" +
	"\x12BatchSearchRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12+\n" +
	"\aqueries\x18\x02 \x03(\v2\x11.barq.SearchQueryR\aqueries\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\rR\x04topK\"6\n" +
	"\fQueryResults\x12&\n" +
	"\x04hits\x18\x01 \x03(\v2\x12.barq.SearchResultR\x04hits\"C\n" +
	"\x13BatchSearchResponse\x12,\n" +
	"\aresults\x18\x01 \x03(\v2\x12.barq.QueryResultsR\aresults*\xbf\x01\n" +
	"\x11InsertStatusState\x12#\n" +
	"\x1fINSERT_STATUS_STATE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aINSERT_STATUS_STATE_QUEUED\x10\x01\x12\"\n" +
	"\x1eINSERT_STATUS_STATE_PROCESSING\x10\x02\x12!\n" +
	"\x1dINSERT_STATUS_STATE_SUCCEEDED\x10\x03\x12\x1e\n" +
	"\x1aINSERT_STATUS_STATE_FAILED\x10\x04*s\n" +
	"\vConsistency\x12\x1b\n" +
	"\x17CONSISTENCY_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CONSISTENCY_PRIMARY\x10\x01\x12\x19\n" +
	"\x15CONSISTENCY_FOLLOWERS\x10\x02\x12\x13\n" +
	"\x0fCONSISTENCY_ANY\x10\x03*t\n" +
	"\n" +
	"MetricKind\x12\x1b\n" +
	"\x17METRIC_KIND_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13METRIC_KIND_COUNTER\x10\x01\x12\x15\n" +
	"\x11METRIC_KIND_GAUGE\x10\x02\x12\x19\n" +
	"\x15METRIC_KIND_HISTOGRAM\x10\x03*\x7f\n" +
	"\fSegmentState\x12\x1d\n" +
	"\x19SEGMENT_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SEGMENT_STATE_GROWING\x10\x01\x12\x18\n" +
	"\x14SEGMENT_STATE_SEALED\x10\x02\x12\x1b\n" +
	"\x17SEGMENT_STATE_COMPACTED\x10\x03*\x91\x01\n" +
	"\vClusterMode\x12\x1c\n" +
	"\x18CLUSTER_MODE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CLUSTER_MODE_SINGLE_NODE\x10\x01\x12#\n" +
	"\x1fCLUSTER_MODE_ROUTED_REPLICATION\x10\x02\x12!\n" +
	"\x1dCLUSTER_MODE_CONSENSUS_BACKED\x10\x03*\x9e\x01\n" +
	"\x0fWriteDurability\x12 \n" +
	"\x1cWRITE_DURABILITY_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bWRITE_DURABILITY_NODE_LOCAL\x10\x01\x12!\n" +
	"\x1dWRITE_DURABILITY_PRIMARY_ONLY\x10\x02\x12%\n" +
	"!WRITE_DURABILITY_CONSENSUS_QUORUM\x10\x03*q\n" +
	"\n" +
	"IndexState\x12\x1b\n" +
	"\x17INDEX_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14INDEX_STATE_BUILDING\x10\x01\x12\x15\n" +
	"\x11INDEX_STATE_READY\x10\x02\x12\x15\n" +
	"\x11INDEX_STATE_STALE\x10\x032\xae\x06\n" +
	"\x04Barq\x123\n" +
	"\x06Status\x12\x13.barq.StatusRequest\x1a\x14.barq.StatusResponse\x12Q\n" +
	"\x10CreateCollection\x12\x1d.barq.CreateCollectionRequest\x1a\x1e.barq.CreateCollectionResponse\x123\n" +
	"\x06Insert\x12\x13.barq.InsertRequest\x1a\x14.barq.InsertResponse\x12=\n" +
	"\vInsertAsync\x12\x13.barq.InsertRequest\x1a\x19.barq.InsertAsyncResponse\x12N\n" +
	"\x0fGetInsertStatus\x12\x1c.barq.GetInsertStatusRequest\x1a\x1d.barq.GetInsertStatusResponse\x123\n" +
	"\x06Search\x12\x13.barq.SearchRequest\x1a\x14.barq.SearchResponse\x12?\n" +
	"\n" +
	"GetMetrics\x12\x17.barq.GetMetricsRequest\x1a\x18.barq.GetMetricsResponse\x12Q\n" +
	"\x10GetClusterStatus\x12\x1d.barq.GetClusterStatusRequest\x1a\x1e.barq.GetClusterStatusResponse\x12K\n" +
	"\x0eGetSegmentInfo\x12\x1b.barq.GetSegmentInfoRequest\x1a\x1c.barq.GetSegmentInfoResponse\x123\n" +
	"\x06Health\x12\x13.barq.HealthRequest\x1a\x14.barq.HealthResponse\x12K\n" +
	"\x0eInsertDocument\x12\x1b.barq.InsertDocumentRequest\x1a\x1c.barq.InsertDocumentResponse\x12B\n" +
	"\vBatchSearch\x12\x18.barq.BatchSearchRequest\x1a\x19.barq.BatchSearchResponseb\x06proto3"

var (
	file_barq_proto_rawDescOnce sync.Once
	file_barq_proto_rawDescData []byte
)

func file_barq_proto_rawDescGZIP() []byte {
	file_barq_proto_rawDescOnce.Do(func() {
		file_barq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_barq_proto_rawDesc), len(file_barq_proto_rawDesc)))
	})
	return file_barq_proto_rawDescData
}

var file_barq_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_barq_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_barq_proto_goTypes = []any{
	(InsertStatusState)(0),               // 0: barq.InsertStatusState
	(Consistency)(0),                     // 1: barq.Consistency
	(MetricKind)(0),                      // 2: barq.MetricKind
	(SegmentState)(0),                    // 3: barq.SegmentState
	(ClusterMode)(0),                     // 4: barq.ClusterMode
	(WriteDurability)(0),                 // 5: barq.WriteDurability
	(IndexState)(0),                      // 6: barq.IndexState
	(*StatusRequest)(nil),                // 7: barq.StatusRequest
	(*StatusResponse)(nil),               // 8: barq.StatusResponse
	(*HealthRequest)(nil),                // 9: barq.HealthRequest
	(*HealthResponse)(nil),               // 10: barq.HealthResponse
	(*CreateCollectionRequest)(nil),      // 11: barq.CreateCollectionRequest
	(*CreateCollectionResponse)(nil),     // 12: barq.CreateCollectionResponse
	(*InsertOptions)(nil),                // 13: barq.InsertOptions
	(*InsertRequest)(nil),                // 14: barq.InsertRequest
	(*InsertResponse)(nil),               // 15: barq.InsertResponse
	(*InsertAsyncResponse)(nil),          // 16: barq.InsertAsyncResponse
	(*GetInsertStatusRequest)(nil),       // 17: barq.GetInsertStatusRequest
	(*GetInsertStatusResponse)(nil),      // 18: barq.GetInsertStatusResponse
	(*InsertDocumentRequest)(nil),        // 19: barq.InsertDocumentRequest
	(*InsertDocumentResponse)(nil),       // 20: barq.InsertDocumentResponse
	(*SearchOptions)(nil),                // 21: barq.SearchOptions
	(*SearchRequest)(nil),                // 22: barq.SearchRequest
	(*SearchResult)(nil),                 // 23: barq.SearchResult
	(*SearchResponse)(nil),               // 24: barq.SearchResponse
	(*GetMetricsRequest)(nil),            // 25: barq.GetMetricsRequest
	(*MetricDefinition)(nil),             // 26: barq.MetricDefinition
	(*TenantMemorySample)(nil),           // 27: barq.TenantMemorySample
	(*CollectionMemorySample)(nil),       // 28: barq.CollectionMemorySample
	(*CollectionWalSample)(nil),          // 29: barq.CollectionWalSample
	(*CollectionSegmentFileSample)(nil),  // 30: barq.CollectionSegmentFileSample
	(*CollectionSegmentStateSample)(nil), // 31: barq.CollectionSegmentStateSample
	(*StorageMetrics)(nil),               // 32: barq.StorageMetrics
	(*GetMetricsResponse)(nil),           // 33: barq.GetMetricsResponse
	(*GetClusterStatusRequest)(nil),      // 34: barq.GetClusterStatusRequest
	(*GetClusterStatusResponse)(nil),     // 35: barq.GetClusterStatusResponse
	(*GetSegmentInfoRequest)(nil),        // 36: barq.GetSegmentInfoRequest
	(*SegmentCount)(nil),                 // 37: barq.SegmentCount
	(*CollectionSegmentInfo)(nil),        // 38: barq.CollectionSegmentInfo
	(*GetSegmentInfoResponse)(nil),       // 39: barq.GetSegmentInfoResponse
	(*SearchQuery)(nil),                  // 40: barq.SearchQuery
	(*BatchSearchRequest)(nil),           // 41: barq.BatchSearchRequest
	(*QueryResults)(nil),                 // 42: barq.QueryResults
	(*BatchSearchResponse)(nil),          // 43: barq.BatchSearchResponse
}
var file_barq_proto_depIdxs = []int32{
	13, // 0: barq.InsertRequest.options:type_name -> barq.InsertOptions
	0,  // 1: barq.GetInsertStatusResponse.state:type_name -> barq.InsertStatusState
	1,  // 2: barq.SearchOptions.consistency:type_name -> barq.Consistency
	21, // 3: barq.SearchRequest.options:type_name -> barq.SearchOptions
	23, // 4: barq.SearchResponse.results:type_name -> barq.SearchResult
	2,  // 5: barq.MetricDefinition.kind:type_name -> barq.MetricKind
	3,  // 6: barq.CollectionSegmentFileSample.state:type_name -> barq.SegmentState
	3,  // 7: barq.CollectionSegmentStateSample.state:type_name -> barq.SegmentState
	27, // 8: barq.StorageMetrics.tenant_memory_bytes:type_name -> barq.TenantMemorySample
	28, // 9: barq.StorageMetrics.collection_memory_bytes:type_name -> barq.CollectionMemorySample
	29, // 10: barq.StorageMetrics.collection_wal:type_name -> barq.CollectionWalSample
	30, // 11: barq.StorageMetrics.collection_segment_files:type_name -> barq.CollectionSegmentFileSample
	31, // 12: barq.StorageMetrics.collection_segment_states:type_name -> barq.CollectionSegmentStateSample
	26, // 13: barq.GetMetricsResponse.definitions:type_name -> barq.MetricDefinition
	32, // 14: barq.GetMetricsResponse.storage:type_name -> barq.StorageMetrics
	4,  // 15: barq.GetClusterStatusResponse.mode:type_name -> barq.ClusterMode
	5,  // 16: barq.GetClusterStatusResponse.write_durability:type_name -> barq.WriteDurability
	3,  // 17: barq.SegmentCount.state:type_name -> barq.SegmentState
	3,  // 18: barq.CollectionSegmentInfo.current_state:type_name -> barq.SegmentState
	6,  // 19: barq.CollectionSegmentInfo.index_state:type_name -> barq.IndexState
	37, // 20: barq.CollectionSegmentInfo.segment_counts:type_name -> barq.SegmentCount
	38, // 21: barq.GetSegmentInfoResponse.collections:type_name -> barq.CollectionSegmentInfo
	40, // 22: barq.BatchSearchRequest.queries:type_name -> barq.SearchQuery
	23, // 23: barq.QueryResults.hits:type_name -> barq.SearchResult
	42, // 24: barq.BatchSearchResponse.results:type_name -> barq.QueryResults
	7,  // 25: barq.Barq.Status:input_type -> barq.StatusRequest
	11, // 26: barq.Barq.CreateCollection:input_type -> barq.CreateCollectionRequest
	14, // 27: barq.Barq.Insert:input_type -> barq.InsertRequest
	14, // 28: barq.Barq.InsertAsync:input_type -> barq.InsertRequest
	17, // 29: barq.Barq.GetInsertStatus:input_type -> barq.GetInsertStatusRequest
	22, // 30: barq.Barq.Search:input_type -> barq.SearchRequest
	25, // 31: barq.Barq.GetMetrics:input_type -> barq.GetMetricsRequest
	34, // 32: barq.Barq.GetClusterStatus:input_type -> barq.GetClusterStatusRequest
	36, // 33: barq.Barq.GetSegmentInfo:input_type -> barq.GetSegmentInfoRequest
	9,  // 34: barq.Barq.Health:input_type -> barq.HealthRequest
	19, // 35: barq.Barq.InsertDocument:input_type -> barq.InsertDocumentRequest
	41, // 36: barq.Barq.BatchSearch:input_type -> barq.BatchSearchRequest
	8,  // 37: barq.Barq.Status:output_type -> barq.StatusResponse
	12, // 38: barq.Barq.CreateCollection:output_type -> barq.CreateCollectionResponse
	15, // 39: barq.Barq.Insert:output_type -> barq.InsertResponse
	16, // 40: barq.Barq.InsertAsync:output_type -> barq.InsertAsyncResponse
	18, // 41: barq.Barq.GetInsertStatus:output_type -> barq.GetInsertStatusResponse
	24, // 42: barq.Barq.Search:output_type -> barq.SearchResponse
	33, // 43: barq.Barq.GetMetrics:output_type -> barq.GetMetricsResponse
	35, // 44: barq.Barq.GetClusterStatus:output_type -> barq.GetClusterStatusResponse
	39, // 45: barq.Barq.GetSegmentInfo:output_type -> barq.GetSegmentInfoResponse
	10, // 46: barq.Barq.Health:output_type -> barq.HealthResponse
	20, // 47: barq.Barq.InsertDocument:output_type -> barq.InsertDocumentResponse
	43, // 48: barq.Barq.BatchSearch:output_type -> barq.BatchSearchResponse
	37, // [37:49] is the sub-list for method output_type
	25, // [25:37] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_barq_proto_init() }
func file_barq_proto_init() {
	if File_barq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_barq_proto_rawDesc), len(file_barq_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_barq_proto_goTypes,
		DependencyIndexes: file_barq_proto_depIdxs,
		EnumInfos:         file_barq_proto_enumTypes,
		MessageInfos:      file_barq_proto_msgTypes,
	}.Build()
	File_barq_proto = out.File
	file_barq_proto_goTypes = nil
	file_barq_proto_depIdxs = nil
}
