// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: barq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Consistency int32

const (
	Consistency_CONSISTENCY_UNSPECIFIED Consistency = 0
	Consistency_CONSISTENCY_PRIMARY     Consistency = 1
	Consistency_CONSISTENCY_FOLLOWERS   Consistency = 2
	Consistency_CONSISTENCY_ANY         Consistency = 3
)

// Enum value maps for Consistency.
var (
	Consistency_name = map[int32]string{
		0: "CONSISTENCY_UNSPECIFIED",
		1: "CONSISTENCY_PRIMARY",
		2: "CONSISTENCY_FOLLOWERS",
		3: "CONSISTENCY_ANY",
	}
	Consistency_value = map[string]int32{
		"CONSISTENCY_UNSPECIFIED": 0,
		"CONSISTENCY_PRIMARY":     1,
		"CONSISTENCY_FOLLOWERS":   2,
		"CONSISTENCY_ANY":         3,
	}
)

func (x Consistency) Enum() *Consistency {
	p := new(Consistency)
	*p = x
	return p
}

func (x Consistency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Consistency) Descriptor() protoreflect.EnumDescriptor {
	return file_barq_proto_enumTypes[0].Descriptor()
}

func (Consistency) Type() protoreflect.EnumType {
	return &file_barq_proto_enumTypes[0]
}

func (x Consistency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Consistency.Descriptor instead.
func (Consistency) EnumDescriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{0}
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_barq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{0}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_barq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_barq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_barq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type CreateCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dimension     uint32                 `protobuf:"varint,2,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Metric        string                 `protobuf:"bytes,3,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionRequest) Reset() {
	*x = CreateCollectionRequest{}
	mi := &file_barq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionRequest) ProtoMessage() {}

func (x *CreateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionRequest.ProtoReflect.Descriptor instead.
func (*CreateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCollectionRequest) GetDimension() uint32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *CreateCollectionRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

type CreateCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionResponse) Reset() {
	*x = CreateCollectionResponse{}
	mi := &file_barq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionResponse) ProtoMessage() {}

func (x *CreateCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionResponse.ProtoReflect.Descriptor instead.
func (*CreateCollectionResponse) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCollectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type InsertOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WaitForCommit bool                   `protobuf:"varint,1,opt,name=wait_for_commit,json=waitForCommit,proto3" json:"wait_for_commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertOptions) Reset() {
	*x = InsertOptions{}
	mi := &file_barq_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertOptions) ProtoMessage() {}

func (x *InsertOptions) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertOptions.ProtoReflect.Descriptor instead.
func (*InsertOptions) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{6}
}

func (x *InsertOptions) GetWaitForCommit() bool {
	if x != nil {
		return x.WaitForCommit
	}
	return false
}

type InsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Vector        []float32              `protobuf:"fixed32,3,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,4,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	Options       *InsertOptions         `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_barq_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{7}
}

func (x *InsertRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *InsertRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InsertRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *InsertRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *InsertRequest) GetOptions() *InsertOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_barq_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{8}
}

func (x *InsertResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type InsertAsyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertAsyncResponse) Reset() {
	*x = InsertAsyncResponse{}
	mi := &file_barq_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertAsyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertAsyncResponse) ProtoMessage() {}

func (x *InsertAsyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertAsyncResponse.ProtoReflect.Descriptor instead.
func (*InsertAsyncResponse) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{9}
}

func (x *InsertAsyncResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *InsertAsyncResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type InsertDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Vector        []float32              `protobuf:"fixed32,3,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,4,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertDocumentRequest) Reset() {
	*x = InsertDocumentRequest{}
	mi := &file_barq_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertDocumentRequest) ProtoMessage() {}

func (x *InsertDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertDocumentRequest.ProtoReflect.Descriptor instead.
func (*InsertDocumentRequest) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{10}
}

func (x *InsertDocumentRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *InsertDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InsertDocumentRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *InsertDocumentRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type InsertDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertDocumentResponse) Reset() {
	*x = InsertDocumentResponse{}
	mi := &file_barq_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertDocumentResponse) ProtoMessage() {}

func (x *InsertDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertDocumentResponse.ProtoReflect.Descriptor instead.
func (*InsertDocumentResponse) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{11}
}

func (x *InsertDocumentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SearchOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consistency   Consistency            `protobuf:"varint,1,opt,name=consistency,proto3,enum=barq.Consistency" json:"consistency,omitempty"`
	AllowFallback bool                   `protobuf:"varint,2,opt,name=allow_fallback,json=allowFallback,proto3" json:"allow_fallback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchOptions) Reset() {
	*x = SearchOptions{}
	mi := &file_barq_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchOptions) ProtoMessage() {}

func (x *SearchOptions) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchOptions.ProtoReflect.Descriptor instead.
func (*SearchOptions) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{12}
}

func (x *SearchOptions) GetConsistency() Consistency {
	if x != nil {
		return x.Consistency
	}
	return Consistency_CONSISTENCY_UNSPECIFIED
}

func (x *SearchOptions) GetAllowFallback() bool {
	if x != nil {
		return x.AllowFallback
	}
	return false
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Vector        []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	TopK          uint32                 `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Options       *SearchOptions         `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_barq_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{13}
}

func (x *SearchRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *SearchRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *SearchRequest) GetTopK() uint32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchRequest) GetOptions() *SearchOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,3,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_barq_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{14}
}

func (x *SearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResult) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_barq_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{15}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type SearchQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        []float32              `protobuf:"fixed32,1,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	FilterJson    string                 `protobuf:"bytes,2,opt,name=filter_json,json=filterJson,proto3" json:"filter_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchQuery) Reset() {
	*x = SearchQuery{}
	mi := &file_barq_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchQuery) ProtoMessage() {}

func (x *SearchQuery) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchQuery.ProtoReflect.Descriptor instead.
func (*SearchQuery) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{16}
}

func (x *SearchQuery) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *SearchQuery) GetFilterJson() string {
	if x != nil {
		return x.FilterJson
	}
	return ""
}

type BatchSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Queries       []*SearchQuery         `protobuf:"bytes,2,rep,name=queries,proto3" json:"queries,omitempty"`
	TopK          uint32                 `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSearchRequest) Reset() {
	*x = BatchSearchRequest{}
	mi := &file_barq_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSearchRequest) ProtoMessage() {}

func (x *BatchSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSearchRequest.ProtoReflect.Descriptor instead.
func (*BatchSearchRequest) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{17}
}

func (x *BatchSearchRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *BatchSearchRequest) GetQueries() []*SearchQuery {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *BatchSearchRequest) GetTopK() uint32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type QueryResults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hits          []*SearchResult        `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResults) Reset() {
	*x = QueryResults{}
	mi := &file_barq_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResults) ProtoMessage() {}

func (x *QueryResults) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResults.ProtoReflect.Descriptor instead.
func (*QueryResults) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{18}
}

func (x *QueryResults) GetHits() []*SearchResult {
	if x != nil {
		return x.Hits
	}
	return nil
}

type BatchSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*QueryResults        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSearchResponse) Reset() {
	*x = BatchSearchResponse{}
	mi := &file_barq_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSearchResponse) ProtoMessage() {}

func (x *BatchSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_barq_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSearchResponse.ProtoReflect.Descriptor instead.
func (*BatchSearchResponse) Descriptor() ([]byte, []int) {
	return file_barq_proto_rawDescGZIP(), []int{19}
}

func (x *BatchSearchResponse) GetResults() []*QueryResults {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_barq_proto protoreflect.FileDescriptor

const file_barq_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"barq.proto\x12\x04barq\"\x0f\n" +
	"\rStatusRequest\":\n" +
	"\x0eStatusResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x0f\n" +
	"\rHealthRequest\":\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"c\n" +
	"\x17CreateCollectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tdimension\x18\x02 \x01(\rR\tdimension\x12\x16\n" +
	"\x06metric\x18\x03 \x01(\tR\x06metric\"4\n" +
	"\x18CreateCollectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"7\n" +
	"\rInsertOptions\x12&\n" +
	"\x0fwait_for_commit\x18\x01 \x01(\bR\rwaitForCommit\"\xa9\x01\n" +
	"\rInsertRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x16\n" +
	"\x06vector\x18\x03 \x03(\x02R\x06vector\x12!\n" +
	"\fpayload_json\x18\x04 \x01(\tR\vpayloadJson\x12-\n" +
	"\aoptions\x18\x05 \x01(\v2\x13.barq.InsertOptionsR\aoptions\"*\n" +
	"\x0eInsertResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"P\n" +
	"\x13InsertAsyncResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"\x82\x01\n" +
	"\x15InsertDocumentRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x16\n" +
	"\x06vector\x18\x03 \x03(\x02R\x06vector\x12!\n" +
	"\fpayload_json\x18\x04 \x01(\tR\vpayloadJson\"2\n" +
	"\x16InsertDocumentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"k\n" +
	"\rSearchOptions\x123\n" +
	"\vconsistency\x18\x01 \x01(\x0e2\x11.barq.ConsistencyR\vconsistency\x12%\n" +
	"\x0eallow_fallback\x18\x02 \x01(\bR\rallowFallback\"\x8b\x01\n" +
	"\rSearchRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x16\n" +
	"\x06vector\x18\x02 \x03(\x02R\x06vector\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\rR\x04topK\x12-\n" +
	"\aoptions\x18\x04 \x01(\v2\x13.barq.SearchOptionsR\aoptions\"W\n" +
	"\fSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12!\n" +
	"\fpayload_json\x18\x03 \x01(\tR\vpayloadJson\">\n" +
	"\x0eSearchResponse\x12,\n" +
	"\aresults\x18\x01 \x03(\v2\x12.barq.SearchResultR\aresults\"F\n" +
	"\vSearchQuery\x12\x16\n" +
	"\x06vector\x18\x01 \x03(\x02R\x06vector\x12\x1f\n" +
	"\vfilter_json\x18\x02 \x01(\tR\n" +
	"filterJson\"v\n" +
	"\x12BatchSearchRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12+\n" +
	"\aqueries\x18\x02 \x03(\v2\x11.barq.SearchQueryR\aqueries\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\rR\x04topK\"6\n" +
	"\fQueryResults\x12&\n" +
	"\x04hits\x18\x01 \x03(\v2\x12.barq.SearchResultR\x04hits\"C\n" +
	"\x13BatchSearchResponse\x12,\n" +
	"\aresults\x18\x01 \x03(\v2\x12.barq.QueryResultsR\aresults*s\n" +
	"\vConsistency\x12\x1b\n" +
	"\x17CONSISTENCY_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CONSISTENCY_PRIMARY\x10\x01\x12\x19\n" +
	"\x15CONSISTENCY_FOLLOWERS\x10\x02\x12\x13\n" +
	"\x0fCONSISTENCY_ANY\x10\x032\xfd\x03\n" +
	"\x04Barq\x123\n" +
	"\x06Status\x12\x13.barq.StatusRequest\x1a\x14.barq.StatusResponse\x12Q\n" +
	"\x10CreateCollection\x12\x1d.barq.CreateCollectionRequest\x1a\x1e.barq.CreateCollectionResponse\x123\n" +
	"\x06Insert\x12\x13.barq.InsertRequest\x1a\x14.barq.InsertResponse\x12=\n" +
	"\vInsertAsync\x12\x13.barq.InsertRequest\x1a\x19.barq.InsertAsyncResponse\x123\n" +
	"\x06Search\x12\x13.barq.SearchRequest\x1a\x14.barq.SearchResponse\x123\n" +
	"\x06Health\x12\x13.barq.HealthRequest\x1a\x14.barq.HealthResponse\x12K\n" +
	"\x0eInsertDocument\x12\x1b.barq.InsertDocumentRequest\x1a\x1c.barq.InsertDocumentResponse\x12B\n" +
	"\vBatchSearch\x12\x18.barq.BatchSearchRequest\x1a\x19.barq.BatchSearchResponseb\x06proto3"

var (
	file_barq_proto_rawDescOnce sync.Once
	file_barq_proto_rawDescData []byte
)

func file_barq_proto_rawDescGZIP() []byte {
	file_barq_proto_rawDescOnce.Do(func() {
		file_barq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_barq_proto_rawDesc), len(file_barq_proto_rawDesc)))
	})
	return file_barq_proto_rawDescData
}

var file_barq_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_barq_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_barq_proto_goTypes = []any{
	(Consistency)(0),                 // 0: barq.Consistency
	(*StatusRequest)(nil),            // 1: barq.StatusRequest
	(*StatusResponse)(nil),           // 2: barq.StatusResponse
	(*HealthRequest)(nil),            // 3: barq.HealthRequest
	(*HealthResponse)(nil),           // 4: barq.HealthResponse
	(*CreateCollectionRequest)(nil),  // 5: barq.CreateCollectionRequest
	(*CreateCollectionResponse)(nil), // 6: barq.CreateCollectionResponse
	(*InsertOptions)(nil),            // 7: barq.InsertOptions
	(*InsertRequest)(nil),            // 8: barq.InsertRequest
	(*InsertResponse)(nil),           // 9: barq.InsertResponse
	(*InsertAsyncResponse)(nil),      // 10: barq.InsertAsyncResponse
	(*InsertDocumentRequest)(nil),    // 11: barq.InsertDocumentRequest
	(*InsertDocumentResponse)(nil),   // 12: barq.InsertDocumentResponse
	(*SearchOptions)(nil),            // 13: barq.SearchOptions
	(*SearchRequest)(nil),            // 14: barq.SearchRequest
	(*SearchResult)(nil),             // 15: barq.SearchResult
	(*SearchResponse)(nil),           // 16: barq.SearchResponse
	(*SearchQuery)(nil),              // 17: barq.SearchQuery
	(*BatchSearchRequest)(nil),       // 18: barq.BatchSearchRequest
	(*QueryResults)(nil),             // 19: barq.QueryResults
	(*BatchSearchResponse)(nil),      // 20: barq.BatchSearchResponse
}
var file_barq_proto_depIdxs = []int32{
	7,  // 0: barq.InsertRequest.options:type_name -> barq.InsertOptions
	0,  // 1: barq.SearchOptions.consistency:type_name -> barq.Consistency
	13, // 2: barq.SearchRequest.options:type_name -> barq.SearchOptions
	15, // 3: barq.SearchResponse.results:type_name -> barq.SearchResult
	17, // 4: barq.BatchSearchRequest.queries:type_name -> barq.SearchQuery
	15, // 5: barq.QueryResults.hits:type_name -> barq.SearchResult
	19, // 6: barq.BatchSearchResponse.results:type_name -> barq.QueryResults
	1,  // 7: barq.Barq.Status:input_type -> barq.StatusRequest
	5,  // 8: barq.Barq.CreateCollection:input_type -> barq.CreateCollectionRequest
	8,  // 9: barq.Barq.Insert:input_type -> barq.InsertRequest
	8,  // 10: barq.Barq.InsertAsync:input_type -> barq.InsertRequest
	14, // 11: barq.Barq.Search:input_type -> barq.SearchRequest
	3,  // 12: barq.Barq.Health:input_type -> barq.HealthRequest
	11, // 13: barq.Barq.InsertDocument:input_type -> barq.InsertDocumentRequest
	18, // 14: barq.Barq.BatchSearch:input_type -> barq.BatchSearchRequest
	2,  // 15: barq.Barq.Status:output_type -> barq.StatusResponse
	6,  // 16: barq.Barq.CreateCollection:output_type -> barq.CreateCollectionResponse
	9,  // 17: barq.Barq.Insert:output_type -> barq.InsertResponse
	10, // 18: barq.Barq.InsertAsync:output_type -> barq.InsertAsyncResponse
	16, // 19: barq.Barq.Search:output_type -> barq.SearchResponse
	4,  // 20: barq.Barq.Health:output_type -> barq.HealthResponse
	12, // 21: barq.Barq.InsertDocument:output_type -> barq.InsertDocumentResponse
	20, // 22: barq.Barq.BatchSearch:output_type -> barq.BatchSearchResponse
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_barq_proto_init() }
func file_barq_proto_init() {
	if File_barq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_barq_proto_rawDesc), len(file_barq_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_barq_proto_goTypes,
		DependencyIndexes: file_barq_proto_depIdxs,
		EnumInfos:         file_barq_proto_enumTypes,
		MessageInfos:      file_barq_proto_msgTypes,
	}.Build()
	File_barq_proto = out.File
	file_barq_proto_goTypes = nil
	file_barq_proto_depIdxs = nil
}
