# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import barq_pb2 as barq__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in barq_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BarqStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Status = channel.unary_unary(
                '/barq.Barq/Status',
                request_serializer=barq__pb2.StatusRequest.SerializeToString,
                response_deserializer=barq__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.CreateCollection = channel.unary_unary(
                '/barq.Barq/CreateCollection',
                request_serializer=barq__pb2.CreateCollectionRequest.SerializeToString,
                response_deserializer=barq__pb2.CreateCollectionResponse.FromString,
                _registered_method=True)
        self.Insert = channel.unary_unary(
                '/barq.Barq/Insert',
                request_serializer=barq__pb2.InsertRequest.SerializeToString,
                response_deserializer=barq__pb2.InsertResponse.FromString,
                _registered_method=True)
        self.InsertAsync = channel.unary_unary(
                '/barq.Barq/InsertAsync',
                request_serializer=barq__pb2.InsertRequest.SerializeToString,
                response_deserializer=barq__pb2.InsertAsyncResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/barq.Barq/Search',
                request_serializer=barq__pb2.SearchRequest.SerializeToString,
                response_deserializer=barq__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/barq.Barq/Health',
                request_serializer=barq__pb2.HealthRequest.SerializeToString,
                response_deserializer=barq__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.InsertDocument = channel.unary_unary(
                '/barq.Barq/InsertDocument',
                request_serializer=barq__pb2.InsertDocumentRequest.SerializeToString,
                response_deserializer=barq__pb2.InsertDocumentResponse.FromString,
                _registered_method=True)
        self.BatchSearch = channel.unary_unary(
                '/barq.Barq/BatchSearch',
                request_serializer=barq__pb2.BatchSearchRequest.SerializeToString,
                response_deserializer=barq__pb2.BatchSearchResponse.FromString,
                _registered_method=True)


class BarqServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Insert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertAsync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Legacy RPCs kept temporarily while SDKs migrate to the canonical contract.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BarqServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=barq__pb2.StatusRequest.FromString,
                    response_serializer=barq__pb2.StatusResponse.SerializeToString,
            ),
            'CreateCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCollection,
                    request_deserializer=barq__pb2.CreateCollectionRequest.FromString,
                    response_serializer=barq__pb2.CreateCollectionResponse.SerializeToString,
            ),
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=barq__pb2.InsertRequest.FromString,
                    response_serializer=barq__pb2.InsertResponse.SerializeToString,
            ),
            'InsertAsync': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertAsync,
                    request_deserializer=barq__pb2.InsertRequest.FromString,
                    response_serializer=barq__pb2.InsertAsyncResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=barq__pb2.SearchRequest.FromString,
                    response_serializer=barq__pb2.SearchResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=barq__pb2.HealthRequest.FromString,
                    response_serializer=barq__pb2.HealthResponse.SerializeToString,
            ),
            'InsertDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertDocument,
                    request_deserializer=barq__pb2.InsertDocumentRequest.FromString,
                    response_serializer=barq__pb2.InsertDocumentResponse.SerializeToString,
            ),
            'BatchSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchSearch,
                    request_deserializer=barq__pb2.BatchSearchRequest.FromString,
                    response_serializer=barq__pb2.BatchSearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'barq.Barq', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('barq.Barq', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Barq(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barq.Barq/Status',
            barq__pb2.StatusRequest.SerializeToString,
            barq__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barq.Barq/CreateCollection',
            barq__pb2.CreateCollectionRequest.SerializeToString,
            barq__pb2.CreateCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barq.Barq/Insert',
            barq__pb2.InsertRequest.SerializeToString,
            barq__pb2.InsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertAsync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barq.Barq/InsertAsync',
            barq__pb2.InsertRequest.SerializeToString,
            barq__pb2.InsertAsyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barq.Barq/Search',
            barq__pb2.SearchRequest.SerializeToString,
            barq__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barq.Barq/Health',
            barq__pb2.HealthRequest.SerializeToString,
            barq__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barq.Barq/InsertDocument',
            barq__pb2.InsertDocumentRequest.SerializeToString,
            barq__pb2.InsertDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barq.Barq/BatchSearch',
            barq__pb2.BatchSearchRequest.SerializeToString,
            barq__pb2.BatchSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
